- .gitignore
- README.md
- src/index.ts
- src/parallelshell.ts
Here's a few screenshots of what the report described in #14 could look like:
Unfortunately, showing exit codes seems a bit pointless, since at least in my test yarn always seemed to be returning `1` on error, no matter what code the underlying script returned. I'll look into this a bit more.
What do you think? @spion
> Feature: Execution Report

- src/index.ts
Yarn has introduced a new format for workspaces:
https://yarnpkg.com/blog/2018/02/15/nohoist/
Make sure we allow this new format when finding the packages globs
> Allow workspaces in new format

- package.json
- yarn.lock
chalk includes it's own type definitions, use these instead.
Fixes https://github.com/whoeverest/wsrun/issues/22
> Remove deprecated @types/chalk

- src/run-graph.ts
we'll no longer see "package has no  scriptname script [...]"
> removed extra space in skipping missing log output

- src/cmd-process.ts
- src/enums.ts
- src/run-graph.ts
So what happens here is that the CmdProcesses are added to the .children array well before they are actually started. In serial+fast-exit, the whole thing is called off before they start. Hence exitCode doesn't correspond to any resolvable promise, and the the whole thing unravels [1], and the process exits before .checkResultsAndReport can be called, let alone process.exit(1).
[1] https://stackoverflow.com/questions/46914025/node-exits-without-error-and-doesnt-await-promise-event-callback
Replace waiting on exitCode with waiting on generalised "result" (which might be "Cancelled", or a normal code), to handle cases where a command might be cancelled before it starts/finishes.
> Issue 28: Propagate exit codes when combining --serial and --fast-exit

- src/cmd-process.ts
Currently the `FORCE_COLOR` environment variable is set to one of the string values `"true"` or `"undefined"`. Both of these are interpreted as truthy values.
> Set FORCE_COLOR to correct values

- src/cmd-process.ts
`chalk` v2 supports a `FORCE_COLOR` environment variable having values `0` or `1` to explicitly disable or enable colors.
https://github.com/chalk/chalk/tree/v2.4.2#chalksupportscolor
`chalk` v1 treats any value as force enable.
https://github.com/chalk/chalk/tree/v1.1.3#chalksupportscolor
This change will make `wsrun` support both versions of `chalk`.
> Not setting FORCE_COLOR=0, supporting chalk 1

- src/index.ts
- src/workspace.ts
- tests/basic.ts
- tests/test.util.ts
Great project. Ran into a not so friendly error message when I had a misconfigured package with no `name` field. Tracked it down, but figured it'd be nice if there wasn't an exposed error from `minimatch` if this happened.
> Gracefully handle misconfigured packages with no name

- src/run-graph.ts
- tests/__snapshots__/basic.ts.snap
- tests/basic.ts
The path rewriting was still happening in the prefixer
TODO: decide whether we want to bump major again. Technically we published 4.0.x without an actual breaking change due to no path rewriting
> fix(rewriting):actually disable path rewriting by default

- .github/semantic.yml
Add config to check only PR titles. This config is for https://github.com/probot/semantic-pull-requests bot.
> chore: Add config for semantic-pull-requests

- src/cmd-process.ts
- src/run-graph.ts
- tests/basic.ts
Arguments are not being passed to the CmdProcess, resulting with bogus path rewrites, e.g "src/some-service.ts" for the "app-backend" package would be rewritten as " ../../app-backend/src/some-service.ts"
> fix: path rewriting did not work correctly

- src/workspace.ts
> fix: wsrun doesn't mimick yarn workspace resolution

- README.md
- src/index.ts
This allows to write short form of commands. The focus of the script becomes the script that should be run, and not the arguments to `wsrun`.
For example:
`wsrun -slem test`
instead of
`wsrun --serial --collect-logs --fast-exit --exclude-missing test`
Also cleaned up some code, to use default values in the program options.
> feat: add default values and aliases to cmd line args

- package.json
- src/cmd-process.ts
- src/console.spec.ts
- src/console.ts
- src/run-graph.ts
- yarn.lock
There are two commits in this PR
Keep the order between stdout and stderr. It is confusing to have all of stderr at the end of the output, because it loses context. Now the output is in the same order as if there was no buffering of output.
If you run with `--collect-logs` you have to wait for each package process to be completed before any output is shown.
With this PR, one process at the time is allowed to write straight to console out. This means that you will see the output as it is generated, for one of the parallel processes. The other processes will be buffered as usual.
When the process that writes straight to console out is done, the next process is picked, its log buffer is flushed, and it is allowed to write to console out.
The result is that the output of running in parallel …
> fix: Output order and streaming preservation for collect-logs

- .vscode/settings.json
- README.md
- package.json
- src/filter-changed-packages.spec.ts
- src/filter-changed-packages.ts
- src/index.ts
- src/run-graph.ts
- yarn.lock
As discussed in https://github.com/hfour/wsrun/issues/58, this PR adds a new option to wsrun to only run packages which have been changed from a supplied branch. It works exactly like `jest --changedSince=master`.
It uses `jest-changed-files` internally.
> feat: Add 'changedSince' option

- src/index.ts
- src/rev-deps.spec.ts
- src/rev-deps.ts
- src/run-graph.ts
This PR adds an option to run the specified command on the resolved packages (whether resolved by `changedSince`, glob or naming specific packages) and **their dependents**. 
For example, if you have 3 packages `A`, `B` and `C`, with dependency chain `pA` -> `pB` -> `pC`, if you use `wsrun -revDeps -c test pC` the `test` command will be run on `pA` and `pB` also because they're dependent on the `pC` package.
Tests are missing, will add them when we agree on implementation.
> feat: Add `revDeps` feature

- README.md
In examples, the `--ifDependency` option is incorrectly written `--if-dependency`.
> docs: fix README.md to fix --ifDependency name

- package.json
- src/index.ts
- yarn.lock
The yargs package (used for processing commandline arguments) is bumped to v13. v13 is the minimum version which receives security updates.
> chore: Bump yargs version

- src/cmd-process.ts
Hello, 
I have a problem with a package called `@applitools/eyes-storybook` under `wsrun`. 
Basically, it spawns a process here: https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-storybook/src/storybookConnector.js#L113
The running process is a dev-server of Storybook, which can be found here emitting colored output:
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/build-dev.js#L218
This colored output gets incorrectly delivered (with encoded colors) to this line: 
https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-storybook/src/storybookConnector.js#L74
which fails to match it via regex, which expects no colored output. 
I don't think it's a good idea to make this regex harder to read and it's just better to allow …
> improvement: allow overriding FORCE_COLOR 

- src/run-graph.ts
When running `wsrun` with `--collect-logs` option, all processes use the same Prefixer instance which has internal state (the last package that used the prefixer). This caused really weird logs, which are grouped but have unnecessary package headings:
```
$ wsrun--series --bin runner -p 'package-*' --collect-logs -c test:backend
package-1
| $ sleep 3 && jest --runInBand --forceExit
package-1
| dropdb not found. Please install the postgres CLI tools on your local machine to create a test db
| createdb not found. Please install the postgres CLI tools on your local machine to create a test db
| `runner test:backend` failed with exit code 1
package-2
| $ jest --runInBand --forceExit
package-2
| dropdb not found. Please install the postgres CLI tools on your local machine to create a test db
| …
```
> fix: Collected logs shouldn't have multiple package name headings
